"use client";
import { useMemo, useState } from "react";
import type { CustomerRow } from "./page";
const yen = new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY", maximumFractionDigits: 0 });

export function CustomerLedger({ customers }: { customers: CustomerRow[] }) {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<CustomerRow | null>(null);
  const rows = useMemo(() => customers.filter((c) => `${c.name} ${c.phone ?? ""} ${c.email ?? ""}`.toLowerCase().includes(query.toLowerCase())), [customers, query]);
  const visibleRows = rows.slice(0, 100);
  return <main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue-700">顧客管理</p><h1 className="mt-1 text-2xl font-semibold">顧客台帳</h1><p className="mt-1 text-sm text-neutral-500">予約情報から連絡先・宿泊履歴・累計利用額を自動集約します。</p></div><label className="block text-xs font-medium text-neutral-600">顧客を検索<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="名前・電話・メール" className="mt-1 min-h-11 w-full rounded-lg border border-neutral-300 px-3 text-base sm:w-72" /></label></div>
    <p className="mt-4 text-xs text-neutral-500">{rows.length}件中 {visibleRows.length}件を表示</p><div className="mt-2 overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-neutral-50 text-xs text-neutral-600"><tr><th className="px-4 py-3">顧客</th><th className="px-4 py-3">連絡先</th><th className="px-4 py-3 text-right">宿泊回数</th><th className="px-4 py-3 text-right">累計利用額</th><th className="px-4 py-3">最終利用</th><th className="px-4 py-3"><span className="sr-only">操作</span></th></tr></thead><tbody className="divide-y divide-neutral-100">{visibleRows.map((c) => <tr key={c.key} className="hover:bg-neutral-50"><td className="px-4 py-3 font-medium">{c.name}</td><td className="px-4 py-3 text-neutral-600"><div>{c.phone || "電話なし"}</div><div>{c.email || "メールなし"}</div></td><td className="px-4 py-3 text-right tabular-nums">{c.stays}回</td><td className="px-4 py-3 text-right font-medium tabular-nums">{yen.format(c.total)}</td><td className="px-4 py-3 tabular-nums">{c.lastStay}</td><td className="px-4 py-3 text-right"><button onClick={() => setSelected(c)} className="min-h-11 rounded-lg border border-neutral-300 px-3 font-medium hover:bg-neutral-100">履歴・注意事項</button></td></tr>)}</tbody></table></div>{!rows.length && <p className="p-10 text-center text-sm text-neutral-500">該当する顧客はいません。</p>}</div>
    {selected && <div className="fixed inset-0 z-50 flex bg-black/40 sm:items-center sm:justify-center sm:p-6" onClick={(e) => e.target === e.currentTarget && setSelected(null)}><section className="h-full w-full overflow-auto bg-white p-5 sm:h-auto sm:max-h-[85vh] sm:max-w-3xl sm:rounded-xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{selected.name}</h2><p className="mt-1 text-sm text-neutral-500">{selected.phone || "電話なし"} / {selected.email || "メールなし"}</p></div><button onClick={() => setSelected(null)} className="h-11 rounded-lg px-4 hover:bg-neutral-100" aria-label="閉じる">閉じる</button></div><h3 className="mt-6 font-semibold">宿泊履歴</h3><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[580px] text-sm"><tbody className="divide-y">{selected.history.map((h) => <tr key={h.id}><td className="py-3">{h.dates}</td><td>{h.property} / {h.room}</td><td className="text-right tabular-nums">{yen.format(h.amount)}</td><td className="pl-3">{h.status}</td></tr>)}</tbody></table></div><h3 className="mt-6 font-semibold">注意事項・予約メモ</h3><div className="mt-2 space-y-2">{selected.notes.length ? selected.notes.map((n, i) => <p key={i} className="whitespace-pre-wrap rounded-lg bg-amber-50 p-3 text-sm text-amber-950">{n}</p>) : <p className="text-sm text-neutral-500">登録なし</p>}</div></section></div>}
  </main>;
}
